name: YDB Hibernate Dialect V5 CI with Maven

on:
  push:
    paths:
      - 'hibernate-dialect-v5/**'
    branches:
      - main
  pull_request:
    paths:
      - 'hibernate-dialect-v5/**'
    types:
      - opened
      - reopened
      - edited

env:
  MAVEN_ARGS: --batch-mode --update-snapshots -Dstyle.color=always

jobs:
  build:
    name: YDB Java Hibernate Dialect V5
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '8', '11', '17' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{matrix.java}}
        uses: actions/setup-java@v4
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
          cache: maven

      - name: Extract Hibernate Dialect version
        working-directory: ./hibernate-dialect-v5
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "HIBERNATE_DIALECT_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Download Hibernate Dialect dependencies
        working-directory: ./hibernate-dialect-v5
        run: mvn $MAVEN_ARGS dependency:go-offline

      - name: Build Hibernate Dialect
        working-directory: ./hibernate-dialect-v5
        run: mvn $MAVEN_ARGS install

      - uses: actions/checkout@v4
        with:
          repository: ydb-platform/ydb-java-examples
          ref: master
          path: examples

      - name: Download dependencies
        working-directory: ./examples/jdbc/spring-data-jpa-v5
        run: mvn $MAVEN_ARGS -Dhibernate.ydb.dialect.version=$HIBERNATE_DIALECT_VERSION dependency:go-offline

      - name: Test examples with Maven
        working-directory: ./examples/jdbc/spring-data-jpa-v5
        run: mvn $MAVEN_ARGS -Dhibernate.ydb.dialect.version=$HIBERNATE_DIALECT_VERSION test
