name: Publish YDB Flyway Dialect

on:
  push:
    tags:
      - 'flyway-ydb/v[0-9]+.[0-9]+.[0-9]+-.*'

env:
  MAVEN_ARGS: --batch-mode --no-transfer-progress -Dstyle.color=always

jobs:
  validate:
    name: Validate YDB Flyway Dialect
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract Flyway dialect version
        working-directory: ./flyway-dialect
        run: |
          FLYWAY_DIALECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "FLYWAY_DIALECT_VERSION=$FLYWAY_DIALECT_VERSION" >> "$GITHUB_ENV"

      - name: Fail workflow if version is snapshot
        if: endsWith(env.FLYWAY_DIALECT_VERSION, 'SNAPSHOT')
        uses: actions/github-script@v6
        with:
          script: core.setFailed('SNAPSHOT version cannot be published')

      - name: Fail workflow if version is not equal to tag name
        if: format('flyway-ydb/v{0}', env.FLYWAY_DIALECT_VERSION) != github.ref_name
        uses: actions/github-script@v6
        with:
          script: core.setFailed('Release name must be equal to project version')

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Download dependencies
        working-directory: ./flyway-dialect
        run: mvn $MAVEN_ARGS dependency:go-offline

      - name: Build with Maven
        working-directory: ./flyway-dialect
        run: mvn $MAVEN_ARGS package

  publish:
    name: Publish YDB Flyway Dialect
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Install gpg secret key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.MAVEN_OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG

      - uses: actions/checkout@v4

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
          server-id: ossrh-s01
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish package
        working-directory: ./flyway-dialect
        run: mvn $MAVEN_ARGS -Possrh-s01 -Dgpg.passphrase=${{ secrets.MAVEN_OSSRH_GPG_PASSWORD }} clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_OSSRH_TOKEN }}
